### ISSUE TITLE
CSS样式

### ISSUE THREAD

**Issue by markyong** [ZEROKISEKI/hexo-theme-cube#1]
为什么我部署完后页面的CSS好像没有用到，页面乱码，help thanks

**Comment by ZEROKISEKI** [comment]
你可以在chrome浏览器f12打开开发者工具，然后刷新网页查看network，如果有很多文件都是failed 404(包括JS文件)，可能是你的Hexo站点的_config.yml文件的url和root不在顶层目录：
```
   
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /

```

如果不是顶层目录的问题，你可以先清除hexo缓存之后重新部署(或者先查看本地是否有问题):

```

    hexo clean
    hexo g
    hexo s 
    hexo d

```

你的站点是哪个? 我可以帮你看一下

**Comment by markyong** [comment]
并不是的，之前其他的主题都是可以的。https://markyong.github.io/ 这是我的站点。

**Comment by ZEROKISEKI** [comment]
我看了下你的github.io的repo，发现你的index.html都是缺了头部的部分(加载css文件的部分)，刚才我自己也试了一次搭建一个[github.io](https://github.com/ZEROKISEKI/ZEROKISEKI.github.io)，并且加了强制https, 发现是没有问题的[https://zerokiseki.github.io](https://zerokiseki.github.io)，你可能是在hexo g生成文件这个部分出了问题，看了下network，请求了content.json这个文件，但是你的github.io的repo上没有content.json，可能你没有在主题的_config.yml关掉**search**选项,  你可以尝试在你的Hexo站点(非主题目录)下安装`hexo-generator-json-content`:

```
      npm install hexo-generator-json-content --save

```

然后在站点_config.yml下进行配置:

```

jsonContent:
  pages:
    title: true
    text: true
    path: true
    preview: true
  posts:
    title: true
    text: true
    path: true
    preview: true

```

然后重新生成看下index.html中有没有<html>头的部分
